server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com.netflix.discovery.DiscoveryClient: TRACE


---

spring:
  profiles: dev

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true