server:
  port: 8765
  server-header: Web
  error:
    whitelabel:
      enabled: false
  tomcat:
      accesslog:
          enabled: true
          pattern: common

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    registryFetchIntervalSeconds: 1
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90

ribbon:
    ServerListRefreshInterval: 1000  
    ReadTimeout: 60000
    ConnectTimeout: 60000
    OkToRetryOnAllOperations: false
    

zuul:
  health:
    enabled: false
  ignoredServices: "*"
  routes:
    attCompositeService__v1:
      path: /*v1/att/**
      
hystrix:
  command:
    default:
      execution.timeout.enabled: false